### ISSUE TITLE
Bug : Grammar mistake in quickstart->Fullstack->Next page.

### ISSUE THREAD

**Issue by ayushrakesh** [teamhanko/docs#31]
### Checklist

- [X] I could not find a solution in the existing issues or docs.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/teamhanko/hanko/blob/main/CODE_OF_CONDUCT.md).

### Describe the bug

Below I have attached the screenshot of it, you can see that "make" should be "made" in quickstart -> Fullstack -> Next  page. 
Please assign this issue to me.

[ This page ](https://docs.hanko.io/quickstarts/fullstack/next)

![screenshot](https://github.com/teamhanko/hanko/assets/115995339/b91c9a5c-668f-462d-b842-79c942da0b33)

### Reproducing the bug

I have spotted the bug through navigating the website's different sections.

### Hanko Version

v1.0.2

### OS Hanko Backend

Windows

### OS

None

### Environment

None

**Comment by ayushrakesh** [comment]
Please assign above issue to me.

**Comment by lfleischmann** [comment]
This repository is no longer the source of truth for the documentation available at docs.hanko.io. The `docs` directory will be removed in the near future. I will transfer this issue to the new repository responsible for the documentation.

**Comment by Ashutosh-Bhadauriya** [comment]
Hey @ayushrakesh changing "make" to "made", the sentence becomes past tense: "Below, we made a logout button component that you can use anywhere." This would imply that the action has already been completed, which is not the case because we're about to explain/show how to create the logout button component.
