### ISSUE TITLE
Standalone Passkey API: link/reference to non-existent package

### ISSUE THREAD

**Issue by lfleischmann** [teamhanko/docs#54]
[This](https://docs.hanko.io/passkey-api/introduction#example-implementation)  section links to a package (`@teamhanko/passkey-backend-sdk`) that does not (yet?) exist on the official npm registry (or elsewhere?). 

The paragraph also claims that the package "[...] do all of the below for you.". This then is also misleading since the package simply  does not exist.

**Comment by Ashutosh-Bhadauriya** [comment]
Thanks @lfleischmann. @merlindru can you please share the updated link? Thanks!
